backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    format: 'frontmatter'
    create: true
    slug: '{{title}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'lawyers',
          value_field: '{{name}}',
          display_fields: ['name'],
          search_fields: ['name'],
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'offices'
    label: 'Offices'
    folder: 'content/offices'
    identifier_field: location
    format: 'frontmatter'
    create: true
    slug: '{{location}}'
    fields:
      - { label: 'Office Name', name: 'title', widget: string }
      - { label: 'Location', name: 'location', widget: string }
      - { label: 'Description', name: 'body', widget: markdown }
      - { label: 'Address', name: 'address', widget: string }
      - { label: 'Image', name: 'image', widget: image, required: false }
  - name: 'lawyers'
    label: 'Lawyers'
    identifier_field: name
    folder: 'content/lawyers'
    format: 'frontmatter'
    create: true
    slug: '{{name}}'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - {
          label: 'Position',
          name: 'position',
          widget: 'select',
          options:
            [
              'Partner',
              'Senior Associate',
              'Of Counsel',
              'Special Counsel',
              'Junior Of Counsel',
              'Junior Associate',
              'Underbar Associate',
            ],
          default: 'Junior Associate',
        }
      - {
          label: 'Start Date in Current Position',
          name: 'startDate',
          widget: 'date',
        }
      - { label: 'Email', name: 'email', widget: 'string' }
      - { label: 'Mobile', name: 'mobile', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - {
          label: 'Admissions',
          name: 'admissions',
          widget: 'list',
          field: { label: 'Admission', name: 'admission', widget: 'string' },
        }
      - {
          label: 'Education',
          name: 'education',
          widget: 'list',
          field: { label: 'Education', name: 'education', widget: 'string' },
        }
      - {
          label: 'Notable Matters',
          name: 'matters',
          widget: 'list',
          field: { label: 'Notable Matter', name: 'notable', widget: 'string' },
        }
      - {
          label: 'Gains and Recognitions',
          name: 'recognitions',
          widget: 'list',
          field:
            {
              label: 'Gains and Recognitions',
              name: 'recognition',
              widget: 'string',
            },
        }
      - label: 'Offices'
        name: 'offices'
        widget: 'relation'
        collection: offices
        value_field: '{{slug}}'
        display_fields: ['location']
        search_fields: ['location']
        multiple: true
      - label: 'Practice Areas'
        name: 'practices'
        widget: 'relation'
        collection: 'practices'
        value_field: '{{slug}}'
        display_fields: ['title']
        search_fields: ['title']
        multiple: true
  - name: 'practices'
    label: 'Practice Areas'
    folder: 'content/practice-areas'
    format: 'frontmatter'
    create: true
    slug: '{{title}}'
    fields:
      - { label: 'Practice Area', name: 'title', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Notable Matters',
          name: 'notables',
          widget: 'list',
          field: { label: 'Notable Matter', name: 'notable', widget: 'string' },
        }
      - label: 'Contact Person/s'
        name: 'contact'
        widget: 'relation'
        collection: 'lawyers'
        value_field: '{{slug}}'
        display_fields: ['name']
        search_fields: ['name']
        multiple: true
      - label: 'Offices'
        name: 'offices'
        widget: 'relation'
        collection: offices
        value_field: '{{slug}}'
        display_fields: ['location']
        search_fields: ['location']
        multiple: true
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'landing'
        label: 'Landing Page'
        file: 'content/landing.yml'
        fields:
          - label: 'Hero'
            name: 'hero'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - { label: 'Subheading', name: 'subheading', widget: 'string' }
              - { label: 'Button', name: 'button', widget: 'string' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Background', name: 'background', widget: 'image' }
              - label: 'Hero Points'
                name: 'points'
                widget: 'list'
                fields:
                  - { label: 'Heading', name: 'heading', widget: 'string' }
                  - { label: 'Details', name: 'details', widget: 'string' }
                  - { label: 'Icon', name: 'icon', widget: 'image' }
          - label: 'Who We Are'
            name: 'about'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - { label: 'Subheading', name: 'subheading', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Button', name: 'button', widget: 'string' }
              - {
                  label: 'Image',
                  name: 'image',
                  widget: image,
                  required: false,
                }
              - label: 'Timeline'
                name: 'timeline'
                widget: 'list'
                fields:
                  - { label: 'Year', name: 'year', widget: 'string' }
                  - { label: 'Event', name: 'event', widget: 'string' }
          - label: 'Offices'
            name: 'offices'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - { label: 'Subheading', name: 'subheading', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - label: 'Locations'
                name: 'locations'
                widget: 'list'
                fields:
                  - { label: 'Image', name: 'image', widget: 'image' }
                  - { label: 'Location', name: 'location', widget: 'string' }
          - label: 'What We Do'
            name: 'practices'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - { label: 'Subheading', name: 'subheading', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - label: 'Practice Areas'
                name: 'practices'
                widget: 'relation'
                collection: 'practices'
                value_field: '{{slug}}'
                display_fields: ['title']
                search_fields: ['title']
                multiple: true
          - label: 'Our Lawyers'
            name: 'lawyers'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - { label: 'Subheading', name: 'subheading', widget: 'string' }
              - label: 'Lawyers'
                name: 'lawyers'
                widget: 'list'
                fields:
                  - { label: 'Name', name: 'name', widget: 'string' }
                  - {
                      label: 'Description',
                      name: 'description',
                      widget: 'text',
                    }
                  - { label: 'Email', name: 'email', widget: 'string' }
                  - { label: 'Phone', name: 'phone', widget: 'string' }
              - { label: 'Image', name: 'image', widget: 'image' }
          - label: 'Gains and Recognitions'
            name: 'awards'
            widget: 'object'
            fields:
              - { label: 'Heading', name: 'heading', widget: 'string' }
              - label: 'Featured Awards (Only 3)'
                name: 'featured'
                widget: 'list'
                fields:
                  - { label: 'Award', name: 'award', widget: 'string' }
                  - { label: 'Year', name: 'year', widget: 'string' }
                  - { label: 'Awarding Body', name: 'body', widget: 'string' }
      - name: 'about'
        label: 'About Page'
        file: 'content/about.md'
        format: 'frontmatter'
        fields:
          - label: 'About Page Heading'
            name: 'heading'
            widget: 'string'
          - label: 'About Page Description'
            name: 'description'
            widget: 'string'
          - label: 'About Page Body'
            name: 'body'
            widget: 'markdown'
      - name: 'lawyers-page'
        label: 'Lawyer Page'
        file: 'content/lawyers-page.yml'
        fields:
          - label: 'Lawyers Page Header'
            name: 'lawyersHeader'
            widget: 'object'
            fields:
              - {
                  label: 'Lawyers Page Heading',
                  name: 'heading',
                  widget: 'string',
                }
              - {
                  label: 'Page Description',
                  name: 'description',
                  widget: 'text',
                }
          - {
              label: 'Lawyers Rank',
              name: 'lawyersRank',
              widget: 'relation',
              collection: 'lawyers',
              value_field: '{{name}}',
              display_fields: ['name'],
              search_fields: ['name'],
              multiple: true,
            }
      - name: 'awards-page'
        label: 'Awards Page'
        file: 'content/awards-page.yml'
        fields:
          - label: 'Awards Page Header'
            name: 'awardsHeader'
            widget: 'object'
            fields:
              - {
                  label: 'Awards Page Heading',
                  name: 'heading',
                  widget: 'string',
                }
              - {
                  label: 'Page Description',
                  name: 'description',
                  widget: 'text',
                }
  - name: 'awards'
    label: 'Awards'
    folder: 'content/awards'
    format: 'frontmatter'
    create: true
    slug: '{{awardbody}}'
    fields:
      - { label: 'Awarding Body', name: 'awardbody', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - {
          label: 'Award',
          name: 'award',
          widget: 'list',
          field: { label: 'Award', name: 'award', widget: 'string' },
        }
